"""update application form fields

Revision ID: a4843ee54200
Revises: 6ee3be88849c
Create Date: 2026-02-13 05:43:56.592274

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a4843ee54200"
down_revision: Union[str, None] = "6ee3be88849c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("applications", sa.Column("birth_date", sa.Date(), nullable=True))
    op.add_column(
        "applications", sa.Column("nationality", sa.String(length=80), nullable=True)
    )
    op.add_column(
        "applications", sa.Column("address", sa.String(length=255), nullable=True)
    )

    gender_enum = sa.Enum("MALE", "FEMALE", name="gender_enum")
    gender_enum.create(op.get_bind(), checkfirst=True)

    op.add_column(
        "applications",
        sa.Column(
            "gender",
            gender_enum,
        ),
    )
    op.add_column(
        "applications", sa.Column("prev_job", sa.String(length=255), nullable=True)
    )
    op.add_column(
        "applications",
        sa.Column("prev_job_duration", sa.String(length=80), nullable=True),
    )
    op.add_column(
        "applications",
        sa.Column("prev_job_leave_reason", sa.String(length=255), nullable=True),
    )
    op.add_column(
        "applications",
        sa.Column(
            "is_married", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
    )
    op.add_column(
        "applications", sa.Column("source", sa.String(length=255), nullable=True)
    )
    op.add_column(
        "applications", sa.Column("desired_salary", sa.String(length=80), nullable=True)
    )
    op.add_column("applications", sa.Column("why_hire_facts", sa.Text(), nullable=True))
    op.create_index(
        op.f("ix_applications_candidate_id"),
        "applications",
        ["candidate_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_applications_vacancy_id"), "applications", ["vacancy_id"], unique=False
    )
    op.drop_column("applications", "city")
    op.drop_column("applications", "skills")
    op.drop_column("applications", "experience_text")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "applications",
        sa.Column("experience_text", sa.TEXT(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "applications",
        sa.Column("skills", sa.TEXT(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "applications",
        sa.Column("city", sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    )
    op.drop_index(op.f("ix_applications_vacancy_id"), table_name="applications")
    op.drop_index(op.f("ix_applications_candidate_id"), table_name="applications")
    op.drop_column("applications", "why_hire_facts")
    op.drop_column("applications", "desired_salary")
    op.drop_column("applications", "source")
    op.drop_column("applications", "is_married")
    op.drop_column("applications", "prev_job_leave_reason")
    op.drop_column("applications", "prev_job_duration")
    op.drop_column("applications", "prev_job")
    op.drop_column("applications", "gender")
    gender_enum = sa.Enum("MALE", "FEMALE", name="gender_enum")
    gender_enum.drop(op.get_bind(), checkfirst=True)
    op.drop_column("applications", "address")
    op.drop_column("applications", "nationality")
    op.drop_column("applications", "birth_date")
    # ### end Alembic commands ###
